export const CREATE_CONTRACT = 'CREATE_CONTRACT';
export const CREATE_CONTRACT_SUCCESS = 'CREATE_CONTRACT_SUCCESS';
export const UPDATED_DATA_USER = 'UPDATED_DATA_USER';
export const UPDATE_DATE_CONTRACT = 'UPDATE_DATE_CONTRACT';
